################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/main.cpp \
../src/myFunc.cpp 

C_SRCS += \
../src/agenda.c \
../src/analysis.c \
../src/argacces.c \
../src/bload.c \
../src/bmathfun.c \
../src/bsave.c \
../src/classcom.c \
../src/classexm.c \
../src/classfun.c \
../src/classinf.c \
../src/classini.c \
../src/classpsr.c \
../src/clsltpsr.c \
../src/commline.c \
../src/conscomp.c \
../src/constrct.c \
../src/constrnt.c \
../src/crstrtgy.c \
../src/cstrcbin.c \
../src/cstrccom.c \
../src/cstrcpsr.c \
../src/cstrnbin.c \
../src/cstrnchk.c \
../src/cstrncmp.c \
../src/cstrnops.c \
../src/cstrnpsr.c \
../src/cstrnutl.c \
../src/default.c \
../src/defins.c \
../src/developr.c \
../src/dffctbin.c \
../src/dffctbsc.c \
../src/dffctcmp.c \
../src/dffctdef.c \
../src/dffctpsr.c \
../src/dffnxbin.c \
../src/dffnxcmp.c \
../src/dffnxexe.c \
../src/dffnxfun.c \
../src/dffnxpsr.c \
../src/dfinsbin.c \
../src/dfinscmp.c \
../src/drive.c \
../src/emathfun.c \
../src/engine.c \
../src/envrnmnt.c \
../src/evaluatn.c \
../src/expressn.c \
../src/exprnbin.c \
../src/exprnops.c \
../src/exprnpsr.c \
../src/extnfunc.c \
../src/factbin.c \
../src/factbld.c \
../src/factcmp.c \
../src/factcom.c \
../src/factfun.c \
../src/factgen.c \
../src/facthsh.c \
../src/factlhs.c \
../src/factmch.c \
../src/factmngr.c \
../src/factprt.c \
../src/factqpsr.c \
../src/factqury.c \
../src/factrete.c \
../src/factrhs.c \
../src/filecom.c \
../src/filertr.c \
../src/generate.c \
../src/genrcbin.c \
../src/genrccmp.c \
../src/genrccom.c \
../src/genrcexe.c \
../src/genrcfun.c \
../src/genrcpsr.c \
../src/globlbin.c \
../src/globlbsc.c \
../src/globlcmp.c \
../src/globlcom.c \
../src/globldef.c \
../src/globlpsr.c \
../src/immthpsr.c \
../src/incrrset.c \
../src/inherpsr.c \
../src/inscom.c \
../src/insfile.c \
../src/insfun.c \
../src/insmngr.c \
../src/insmoddp.c \
../src/insmult.c \
../src/inspsr.c \
../src/insquery.c \
../src/insqypsr.c \
../src/iofun.c \
../src/lgcldpnd.c \
../src/memalloc.c \
../src/miscfun.c \
../src/modulbin.c \
../src/modulbsc.c \
../src/modulcmp.c \
../src/moduldef.c \
../src/modulpsr.c \
../src/modulutl.c \
../src/msgcom.c \
../src/msgfun.c \
../src/msgpass.c \
../src/msgpsr.c \
../src/multifld.c \
../src/multifun.c \
../src/objbin.c \
../src/objcmp.c \
../src/objrtbin.c \
../src/objrtbld.c \
../src/objrtcmp.c \
../src/objrtfnx.c \
../src/objrtgen.c \
../src/objrtmch.c \
../src/parsefun.c \
../src/pattern.c \
../src/pprint.c \
../src/prccode.c \
../src/prcdrfun.c \
../src/prcdrpsr.c \
../src/prdctfun.c \
../src/prntutil.c \
../src/proflfun.c \
../src/reorder.c \
../src/reteutil.c \
../src/retract.c \
../src/router.c \
../src/rulebin.c \
../src/rulebld.c \
../src/rulebsc.c \
../src/rulecmp.c \
../src/rulecom.c \
../src/rulecstr.c \
../src/ruledef.c \
../src/ruledlt.c \
../src/rulelhs.c \
../src/rulepsr.c \
../src/scanner.c \
../src/sortfun.c \
../src/strngfun.c \
../src/strngrtr.c \
../src/symblbin.c \
../src/symblcmp.c \
../src/symbol.c \
../src/sysdep.c \
../src/textpro.c \
../src/tmpltbin.c \
../src/tmpltbsc.c \
../src/tmpltcmp.c \
../src/tmpltdef.c \
../src/tmpltfun.c \
../src/tmpltlhs.c \
../src/tmpltpsr.c \
../src/tmpltrhs.c \
../src/tmpltutl.c \
../src/userdata.c \
../src/userfunctions.c \
../src/utility.c \
../src/watch.c 

OBJS += \
./src/agenda.o \
./src/analysis.o \
./src/argacces.o \
./src/bload.o \
./src/bmathfun.o \
./src/bsave.o \
./src/classcom.o \
./src/classexm.o \
./src/classfun.o \
./src/classinf.o \
./src/classini.o \
./src/classpsr.o \
./src/clsltpsr.o \
./src/commline.o \
./src/conscomp.o \
./src/constrct.o \
./src/constrnt.o \
./src/crstrtgy.o \
./src/cstrcbin.o \
./src/cstrccom.o \
./src/cstrcpsr.o \
./src/cstrnbin.o \
./src/cstrnchk.o \
./src/cstrncmp.o \
./src/cstrnops.o \
./src/cstrnpsr.o \
./src/cstrnutl.o \
./src/default.o \
./src/defins.o \
./src/developr.o \
./src/dffctbin.o \
./src/dffctbsc.o \
./src/dffctcmp.o \
./src/dffctdef.o \
./src/dffctpsr.o \
./src/dffnxbin.o \
./src/dffnxcmp.o \
./src/dffnxexe.o \
./src/dffnxfun.o \
./src/dffnxpsr.o \
./src/dfinsbin.o \
./src/dfinscmp.o \
./src/drive.o \
./src/emathfun.o \
./src/engine.o \
./src/envrnmnt.o \
./src/evaluatn.o \
./src/expressn.o \
./src/exprnbin.o \
./src/exprnops.o \
./src/exprnpsr.o \
./src/extnfunc.o \
./src/factbin.o \
./src/factbld.o \
./src/factcmp.o \
./src/factcom.o \
./src/factfun.o \
./src/factgen.o \
./src/facthsh.o \
./src/factlhs.o \
./src/factmch.o \
./src/factmngr.o \
./src/factprt.o \
./src/factqpsr.o \
./src/factqury.o \
./src/factrete.o \
./src/factrhs.o \
./src/filecom.o \
./src/filertr.o \
./src/generate.o \
./src/genrcbin.o \
./src/genrccmp.o \
./src/genrccom.o \
./src/genrcexe.o \
./src/genrcfun.o \
./src/genrcpsr.o \
./src/globlbin.o \
./src/globlbsc.o \
./src/globlcmp.o \
./src/globlcom.o \
./src/globldef.o \
./src/globlpsr.o \
./src/immthpsr.o \
./src/incrrset.o \
./src/inherpsr.o \
./src/inscom.o \
./src/insfile.o \
./src/insfun.o \
./src/insmngr.o \
./src/insmoddp.o \
./src/insmult.o \
./src/inspsr.o \
./src/insquery.o \
./src/insqypsr.o \
./src/iofun.o \
./src/lgcldpnd.o \
./src/main.o \
./src/memalloc.o \
./src/miscfun.o \
./src/modulbin.o \
./src/modulbsc.o \
./src/modulcmp.o \
./src/moduldef.o \
./src/modulpsr.o \
./src/modulutl.o \
./src/msgcom.o \
./src/msgfun.o \
./src/msgpass.o \
./src/msgpsr.o \
./src/multifld.o \
./src/multifun.o \
./src/myFunc.o \
./src/objbin.o \
./src/objcmp.o \
./src/objrtbin.o \
./src/objrtbld.o \
./src/objrtcmp.o \
./src/objrtfnx.o \
./src/objrtgen.o \
./src/objrtmch.o \
./src/parsefun.o \
./src/pattern.o \
./src/pprint.o \
./src/prccode.o \
./src/prcdrfun.o \
./src/prcdrpsr.o \
./src/prdctfun.o \
./src/prntutil.o \
./src/proflfun.o \
./src/reorder.o \
./src/reteutil.o \
./src/retract.o \
./src/router.o \
./src/rulebin.o \
./src/rulebld.o \
./src/rulebsc.o \
./src/rulecmp.o \
./src/rulecom.o \
./src/rulecstr.o \
./src/ruledef.o \
./src/ruledlt.o \
./src/rulelhs.o \
./src/rulepsr.o \
./src/scanner.o \
./src/sortfun.o \
./src/strngfun.o \
./src/strngrtr.o \
./src/symblbin.o \
./src/symblcmp.o \
./src/symbol.o \
./src/sysdep.o \
./src/textpro.o \
./src/tmpltbin.o \
./src/tmpltbsc.o \
./src/tmpltcmp.o \
./src/tmpltdef.o \
./src/tmpltfun.o \
./src/tmpltlhs.o \
./src/tmpltpsr.o \
./src/tmpltrhs.o \
./src/tmpltutl.o \
./src/userdata.o \
./src/userfunctions.o \
./src/utility.o \
./src/watch.o 

CPP_DEPS += \
./src/main.d \
./src/myFunc.d 

C_DEPS += \
./src/agenda.d \
./src/analysis.d \
./src/argacces.d \
./src/bload.d \
./src/bmathfun.d \
./src/bsave.d \
./src/classcom.d \
./src/classexm.d \
./src/classfun.d \
./src/classinf.d \
./src/classini.d \
./src/classpsr.d \
./src/clsltpsr.d \
./src/commline.d \
./src/conscomp.d \
./src/constrct.d \
./src/constrnt.d \
./src/crstrtgy.d \
./src/cstrcbin.d \
./src/cstrccom.d \
./src/cstrcpsr.d \
./src/cstrnbin.d \
./src/cstrnchk.d \
./src/cstrncmp.d \
./src/cstrnops.d \
./src/cstrnpsr.d \
./src/cstrnutl.d \
./src/default.d \
./src/defins.d \
./src/developr.d \
./src/dffctbin.d \
./src/dffctbsc.d \
./src/dffctcmp.d \
./src/dffctdef.d \
./src/dffctpsr.d \
./src/dffnxbin.d \
./src/dffnxcmp.d \
./src/dffnxexe.d \
./src/dffnxfun.d \
./src/dffnxpsr.d \
./src/dfinsbin.d \
./src/dfinscmp.d \
./src/drive.d \
./src/emathfun.d \
./src/engine.d \
./src/envrnmnt.d \
./src/evaluatn.d \
./src/expressn.d \
./src/exprnbin.d \
./src/exprnops.d \
./src/exprnpsr.d \
./src/extnfunc.d \
./src/factbin.d \
./src/factbld.d \
./src/factcmp.d \
./src/factcom.d \
./src/factfun.d \
./src/factgen.d \
./src/facthsh.d \
./src/factlhs.d \
./src/factmch.d \
./src/factmngr.d \
./src/factprt.d \
./src/factqpsr.d \
./src/factqury.d \
./src/factrete.d \
./src/factrhs.d \
./src/filecom.d \
./src/filertr.d \
./src/generate.d \
./src/genrcbin.d \
./src/genrccmp.d \
./src/genrccom.d \
./src/genrcexe.d \
./src/genrcfun.d \
./src/genrcpsr.d \
./src/globlbin.d \
./src/globlbsc.d \
./src/globlcmp.d \
./src/globlcom.d \
./src/globldef.d \
./src/globlpsr.d \
./src/immthpsr.d \
./src/incrrset.d \
./src/inherpsr.d \
./src/inscom.d \
./src/insfile.d \
./src/insfun.d \
./src/insmngr.d \
./src/insmoddp.d \
./src/insmult.d \
./src/inspsr.d \
./src/insquery.d \
./src/insqypsr.d \
./src/iofun.d \
./src/lgcldpnd.d \
./src/memalloc.d \
./src/miscfun.d \
./src/modulbin.d \
./src/modulbsc.d \
./src/modulcmp.d \
./src/moduldef.d \
./src/modulpsr.d \
./src/modulutl.d \
./src/msgcom.d \
./src/msgfun.d \
./src/msgpass.d \
./src/msgpsr.d \
./src/multifld.d \
./src/multifun.d \
./src/objbin.d \
./src/objcmp.d \
./src/objrtbin.d \
./src/objrtbld.d \
./src/objrtcmp.d \
./src/objrtfnx.d \
./src/objrtgen.d \
./src/objrtmch.d \
./src/parsefun.d \
./src/pattern.d \
./src/pprint.d \
./src/prccode.d \
./src/prcdrfun.d \
./src/prcdrpsr.d \
./src/prdctfun.d \
./src/prntutil.d \
./src/proflfun.d \
./src/reorder.d \
./src/reteutil.d \
./src/retract.d \
./src/router.d \
./src/rulebin.d \
./src/rulebld.d \
./src/rulebsc.d \
./src/rulecmp.d \
./src/rulecom.d \
./src/rulecstr.d \
./src/ruledef.d \
./src/ruledlt.d \
./src/rulelhs.d \
./src/rulepsr.d \
./src/scanner.d \
./src/sortfun.d \
./src/strngfun.d \
./src/strngrtr.d \
./src/symblbin.d \
./src/symblcmp.d \
./src/symbol.d \
./src/sysdep.d \
./src/textpro.d \
./src/tmpltbin.d \
./src/tmpltbsc.d \
./src/tmpltcmp.d \
./src/tmpltdef.d \
./src/tmpltfun.d \
./src/tmpltlhs.d \
./src/tmpltpsr.d \
./src/tmpltrhs.d \
./src/tmpltutl.d \
./src/userdata.d \
./src/userfunctions.d \
./src/utility.d \
./src/watch.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O3 -g3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/%.o: ../src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


